baseurl: /awesome
exclude:
  - includes
  - layouts
  - Gemfile
  - LICENSE
  - README.md
collections:
  common:
    output: true
  cs_resources:
    output: true
  math_resources:
    output: true
permalink: pretty
