baseurl: /awesome
title: LibreIM

collections:
  common:
    output: true
    permalink: /:path/
  math_resources:
    output: true
    permalink: /:path/
  cs_resources:
    output: true
    permalink: /:path/
